# Generated by Django 5.1.7 on 2026-05-24 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OvertimePost",
            fields=[
                ("overtime_id", models.AutoField(primary_key=True, serialize=False)),
                ("work_order", models.CharField(blank=True, max_length=50, null=True)),
                ("date", models.DateField()),
                ("shift", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("hours", models.FloatField()),
                ("location", models.CharField(max_length=50)),
                ("personnel", models.IntegerField()),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("filled", "filled"),
                            ("partial", "partial"),
                            ("assigned", "assigned"),
                            ("cancelled", "cancelled"),
                            ("re-scheduled", "rescheduled"),
                        ],
                        default="partial",
                        max_length=15,
                    ),
                ),
                ("had_forced", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge_num", models.IntegerField(unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("hours", models.FloatField(default=0.0)),
                ("pin", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("email", "email"),
                            ("both", "both"),
                            ("none", "none"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Pat", "Patrol"),
                            ("Sgt", "Seargent"),
                            ("Lt", "Lieutenant"),
                            ("Cmd", "Command Staff"),
                        ],
                        default="Pat",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[("voluntary", "Voluntary"), ("forced", "Forced")],
                        default="voluntary",
                        max_length=10,
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "overtime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.overtimepost",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to="api.users",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.users"
                    ),
                ),
            ],
        ),
    ]
